[package]
name = "neuraldisk_cli"
version = "1.0.0"
authors = ["Rafał Mikrut <mikrutrafal@protonmail.com>"]
edition = "2024"
rust-version = "1.94.1"
description = "CLI frontend of NeuralDisk"
license = "MIT"
homepage = "https://github.com/k-aksha/neural-disk"
repository = "https://github.com/k-aksha/neural-disk"

[dependencies]
clap = { version = "4.5", features = ["derive", "color"] }

log = "0.4.22"
neuraldisk_core = { path = "../neuraldisk_core", version = "1.0.0", features = [] }
indicatif = "0.18"
crossbeam-channel = { version = "0.5", features = [] }
ctrlc = { version = "3.4", features = ["termination"] }
humansize = "2.1"

[features]
default = []
heif = ["neuraldisk_core/heif"]
libraw = ["neuraldisk_core/libraw"]
libavif = ["neuraldisk_core/libavif"]
# Allows to use trash on Linux when using xdg-portal, needed by e.g. flatpak where normal trash access always fails
# No-op on other OSes, it is slower and provides less helpful error messages
xdg_portal_trash = ["neuraldisk_core/xdg_portal_trash"]

no_colors = []

[lints]
workspace = true
